import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen bg-black overflow-hidden">
          {/* Background blobs */}
          <div
            className="absolute w-[500px] h-[500px] rounded-full bg-purple-600/30 blur-3xl"
            style={{
              top: "20%",
              left: "60%",
              transform: "translate(-50%, -50%)",
              animation: "blob1 7s infinite ease-in-out",
            }}
          />
          <div
            className="absolute w-[600px] h-[600px] rounded-full bg-blue-600/20 blur-3xl"
            style={{
              top: "60%",
              left: "30%",
              transform: "translate(-50%, -50%)",
              animation: "blob2 8s infinite ease-in-out",
            }}
          />

          {/* Content */}
          <div className="relative z-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
